apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-config
  namespace: grav
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
