apiVersion: v1
kind: ServiceAccount
metadata:
  name: grav-ssg-sa
  namespace: grav
---
# Argo Workflows needs this to run workflows in the grav namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grav-workflow-role
  namespace: grav
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grav-workflow-rolebinding
  namespace: grav
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grav-workflow-role
subjects:
  - kind: ServiceAccount
    name: grav-ssg-sa
    namespace: grav
